# Generated by Django 5.1 on 2024-09-15 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_image',
            field=models.ImageField(default=1, upload_to='Images/profiles/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='Subject_Image',
            field=models.ImageField(default=1, upload_to='Images/profiles/'),
            preserve_default=False,
        ),
    ]
