# Generated by Django 5.1 on 2024-09-20 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_course_course_image_subject_subject_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='icon',
            field=models.ImageField(default=1, upload_to='Images/profiles/'),
            preserve_default=False,
        ),
    ]
