# Generated by Django 5.1 on 2024-09-22 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_course_end_date_remove_course_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='Time',
            field=models.TimeField(default="10"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='preview',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='whatyoulearn',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='WhatLearn', to='api.course'),
        ),
    ]
