# Generated by Django 5.1 on 2024-09-22 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_video_time_video_preview_alter_whatyoulearn_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='Time',
            field=models.TimeField(null=True),
        ),
    ]
