# Generated by Django 5.1 on 2024-09-22 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_video_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='Time',
            field=models.FloatField(null=True),
        ),
    ]
