# Generated by Django 5.1 on 2024-09-22 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_video_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='Time',
        ),
    ]
