# Generated by Django 5.1 on 2024-09-22 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_video_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='preview',
            field=models.BooleanField(default=False),
        ),
    ]
