# Generated by Django 5.1 on 2024-09-22 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_video_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='Time',
            field=models.FloatField(null=True),
        ),
    ]
