# Generated by Django 5.1 on 2024-09-22 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_module_srnumber_video_srno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='srNumber',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='srNo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
