# Generated by Django 5.1 on 2024-09-22 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_module_srnumber_alter_video_srno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='srNumber',
        ),
        migrations.RemoveField(
            model_name='video',
            name='srNo',
        ),
    ]
