# Generated by Django 5.1 on 2024-09-22 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_module_srnumber_remove_video_srno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='Time',
            field=models.FloatField(default=10.0),
            preserve_default=False,
        ),
    ]
