# Generated by Django 5.1 on 2024-09-22 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_video_time_video_timing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='timing',
        ),
        migrations.AddField(
            model_name='video',
            name='Time',
            field=models.DurationField(null=True),
        ),
    ]
