# Generated by Django 5.1 on 2024-09-22 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_video_timing_video_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='Time',
        ),
        migrations.AddField(
            model_name='video',
            name='text',
            field=models.TextField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
