# Generated by Django 5.1 on 2024-09-22 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_remove_video_time_video_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='preview',
        ),
    ]
