# Generated by Django 5.1 on 2024-09-22 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_remove_video_preview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='text',
        ),
    ]
