# Generated by Django 5.1 on 2024-09-22 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_content_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='text',
        ),
        migrations.RemoveField(
            model_name='video',
            name='text',
        ),
        migrations.AddField(
            model_name='video',
            name='Time',
            field=models.FloatField(null=True),
        ),
    ]
