# Generated by Django 5.1 on 2024-09-22 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_remove_content_text_remove_video_text_video_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='Time',
        ),
    ]
