# Generated by Django 5.1 on 2024-09-22 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_remove_video_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='srNumber',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='duration',
            field=models.DurationField(null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='preview',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='srNo',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_url',
            field=models.URLField(null=True),
        ),
    ]
