# Generated by Django 5.1 on 2024-09-22 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_module_srnumber_video_duration_video_preview_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='Title',
            field=models.TextField(null=True),
        ),
    ]
