# Generated by Django 5.1 on 2024-09-25 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='enrolled_users',
            new_name='enrolled_user',
        ),
    ]
