# Generated by Django 5.1 on 2024-09-25 08:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_rename_enrolled_users_course_enrolled_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='enrolled_user',
            field=models.ManyToManyField(blank=True, related_name='enrolled_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
